---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/12 20:04
---

local backend = require "backend"

local function main()
    local file_name = arg[1];
    if file_name == nil or file_name == "" then
        error("please input your file name")
    end
    local file = io.open(file_name, "r")    -- 使用 io.open() 函数，以只读模式打开文件
    local codes = file:read("a")
    file:close()

    backend.execute(codes)
end

local function handle_exception(msg)
    print("catch exception, error message: " .. tostring(msg))
end

xpcall(main, handle_exception)
