---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/6 15:47
---


local TOKEN_TYPE = {
    EOF = "EOF",
    VAR_PREFIX = "VAR_PREFIX",
    LEFT_PAREN = "LEFT_PAREN",
    RIGHT_PAREN = "RIGHT_PAREN",
    EQUAL = "EQUAL",
    QUOTE = "QUOTE",
    DOU_QUOTE = "DOU_QUOTE",
    PRINT = "PRINT",
    NAME = "NAME"
}

return TOKEN_TYPE

